### ISSUE TITLE
Dear developer, there is an error that appears when I try to run the command python setup.py bdist_wheel.

### ISSUE THREAD

**Issue by Leon1207** [dvlab-research/spconv-plus#4]
Is there something wrong with the version of setuptools? Here is the traceback of the error:

File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/pccm/extension.py", line 78, in build_extension
    lib_path = pccm.builder.build_pybind(ext.cus,
  File "/home/lyd/miniconda3/envs/pcr/lib/python3.8/site-packages/pccm/builder/pybind.py", line 120, in build_pybind
    return ccimport.ccimport(
TypeError: ccimport() got multiple values for argument 'std'

**Comment by yukang2017** [comment]
Hi,

I think this issue is from the version issue of pccm and setuptools. Would you please provide me a detailed environment list, via `conda list`?

Regards,
Yukang Chen

**Comment by Leon1207** [comment]
Thanks! Here is the version information of pccm and setuptools:
setuptools                65.3.0                   pypi_0    pypi
pccm                      0.3.4                    pypi_0    pypi

And here is the whole information of conda list:
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4              pyhd3eb1b0_0    anaconda
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
blas                      1.0                    openblas    anaconda
boltons                   23.0.0          py310h06a4308_0
bottleneck                1.3.5           py310ha9d4c09_0    anaconda
brotlipy                  0.7.0           py310h7f8727e_1002
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cmake                     3.26.1                   pypi_0    pypi
conda                     23.3.1          py310hff52083_0    conda-forge
conda-content-trust       0.1.3           py310h06a4308_0
conda-package-handling    2.0.2           py310h06a4308_0
conda-package-streaming   0.7.0           py310h06a4308_0
cryptography              38.0.4          py310h9ce1e76_0
docker-pycreds            0.4.0                      py_0    conda-forge
einops                    0.6.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.9                h27cfd23_1    anaconda
filelock                  3.10.7                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0           pyhd8ed1ab_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gin-config                0.5.0              pyhd8ed1ab_0    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.31             pyhd8ed1ab_0    conda-forge
h5py                      3.7.0           py310he06866b_0    anaconda
hdf5                      1.10.6               h3ffc7dd_1    anaconda
idna                      3.4             py310h06a4308_0
intel-openmp              2021.4.0          h06a4308_3561
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.1           py310h06a4308_0    anaconda
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_1
libopenblas               0.3.21               h043d6bf_0    anaconda
libprotobuf               3.20.3               he621ea3_0
libstdcxx-ng              11.2.0               h1234567_1
libuuid                   1.41.5               h5eee18b_0
lightning-bolts           0.6.0.post1              pypi_0    pypi
lightning-utilities       0.8.0              pyhd8ed1ab_0    conda-forge
lit                       16.0.0                   pypi_0    pypi
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2                    pypi_0    pypi
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
minkowskiengine           0.5.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0           py310h7f8727e_0
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
networkx                  3.1                      pypi_0    pypi
ninja                     1.10.2               h06a4308_5
ninja-base                1.10.2               hd09550d_5
nomkl                     3.0                           0    anaconda
numexpr                   2.8.4           py310h757a811_0    anaconda
numpy                     1.23.5          py310hac523dd_0
numpy-base                1.23.5          py310h375b286_0    anaconda
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openblas-devel            0.3.21               h06a4308_0    anaconda
openssl                   1.1.1t               h7f8727e_0
packaging                 23.0            py310h06a4308_0
pandas                    1.5.2           py310h1128e8f_0    anaconda
pathtools                 0.1.2                      py_1    conda-forge
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1          py310h06a4308_0
pluggy                    1.0.0           py310h06a4308_1
plyfile                   0.8.1              pyhd8ed1ab_0    conda-forge
pooch                     1.4.0              pyhd3eb1b0_0    anaconda
protobuf                  3.20.3          py310h6a678d5_0
psutil                    5.9.0           py310h5eee18b_0
pycosat                   0.6.4           py310h5eee18b_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd3eb1b0_0
pysocks                   1.7.1           py310h06a4308_0
python                    3.10.9               h7a1cb2a_0
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python_abi                3.10                    2_cp310    conda-forge
pytorch-lightning         2.0.1              pyhd8ed1ab_0    conda-forge
pytz                      2022.7          py310h06a4308_0    anaconda
pyyaml                    6.0             py310h5764c6d_4    conda-forge
readline                  8.2                  h5eee18b_0
requests                  2.28.1          py310h06a4308_0
rich                      13.3.3             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h5eee18b_0
ruamel.yaml.clib          0.2.6           py310h5eee18b_1
scikit-learn              1.2.0           py310h6a678d5_0    anaconda
scipy                     1.10.0          py310heeff2f4_0    anaconda
sentry-sdk                1.19.1             pyhd8ed1ab_0    conda-forge
setproctitle              1.2.2           py310h5764c6d_2    conda-forge
setuptools                65.6.3          py310h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     3.0.5              pyh44b312d_0    conda-forge
sqlite                    3.40.1               h5082296_0
sympy                     1.11.1                   pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0    anaconda
tk                        8.6.12               h1ccaba5_0
toolz                     0.12.0          py310h06a4308_0
torch                     2.0.0                    pypi_0    pypi
torch-scatter             2.1.1                    pypi_0    pypi
torchmetrics              0.11.4             pyhd8ed1ab_0    conda-forge
torchvision               0.15.1                   pypi_0    pypi
tqdm                      4.64.1          py310h06a4308_0
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h04d1e81_0
urllib3                   1.26.14         py310h06a4308_0
wandb                     0.14.1             pyhd8ed1ab_0    conda-forge
wheel                     0.40.0                   pypi_0    pypi
wrapt                     1.14.1          py310h5eee18b_0
xz                        5.2.10               h5eee18b_1
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.8.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstandard                 0.18.0          py310h5eee18b_0

**Comment by coutyou** [comment]
I encountered the same error, too.
I use python3.8 cuda11.4 pytorch==1.12.1 cumm==0.2.8, pccm==0.3.4, wheel==0.38.4, setuptools==66.0.0

**Comment by yukang2017** [comment]
Hi,

Would you please have a try with setuptools==58.0.4?

Regards,
Yukang Chen

**Comment by Leon1207** [comment]
It works! Thank you very much. And it also should be installed by conda `conda install setuptools==58.0.4`, not pip.

**Comment by Leon1207** [comment]
Dear developer!
I found compilation and installation unreliable. When I successfully compile and `import spconv`, I get an error of `No module named 'cumm.gemm'`. Then I uninstalled spconv and recompiled, and the original error `TypeError: ccimport() got multiple values for argument 'std'` came up again. I would like to ask under what environment the author compiled? Thank you very much!

**Comment by yukang2017** [comment]
Hi,

This is weird. I think after you compiled. What you need to do is to install the complied file. 
`pip install path_to_the_spconv_wheel.whl`. Instead of `import spconv` directly.

Anyway, I think it is near the final point.

Regards,
Yukang Chen

**Comment by Leon1207** [comment]
Sincerely thank you for your answer! I will try again.

**Comment by Leon1207** [comment]
Dear developer, there still have some trouble when installing spconv-plus. Could you please pack the conda env for me using `conda env export > environment.yml`? Sincerely thanks!

**Comment by yukang2017** [comment]
Sure!
[environment.yml.zip](https://github.com/dvlab-research/spconv-plus/files/11317599/environment.yml.zip)

**Comment by coutyou** [comment]
In my case, the `TypeError: ccimport() got multiple values for argument 'std'` remains, after `conda install setuptools==58.0.4`🥲

**Comment by coutyou** [comment]
However, for your information, after `pip install ccimport==0.3.7`, the compilation is successful.

**Comment by Leon1207** [comment]
Great! `pip install ccimport==0.3.7` works!

**Comment by fjzpcmj** [comment]
hello authors,  when installing spconv-plus，there are some errors:

/usr/local/miniconda3/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
  warnings.warn(
running bdist_wheel
running build
running build_py
copying spconv/__version__.py -> build/lib.linux-x86_64-3.8/spconv
running egg_info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing entry points to spconv.egg-info/entry_points.txt
writing requirements to spconv.egg-info/requires.txt
writing top-level names to spconv.egg-info/top_level.txt
reading manifest file 'spconv.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'spconv.egg-info/SOURCES.txt'
running build_ext
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
copying build/lib.linux-x86_64-3.8/spconv/core_cc/cumm/gemm/main.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/cumm/gemm
copying build/lib.linux-x86_64-3.8/spconv/core_cc/cumm/common.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/cumm
copying build/lib.linux-x86_64-3.8/spconv/core_cc/cumm/conv/main.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/cumm/conv
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/utils/boxops.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/utils
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/hash/core.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/hash
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops3d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops_cpu2d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops1d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops2d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/__init__.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops_cpu1d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops4d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops_cpu4d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc/csrc/sparse/all/ops_cpu3d.pyi -> build/bdist.linux-x86_64/wheel/spconv/core_cc/csrc/sparse/all
copying build/lib.linux-x86_64-3.8/spconv/core_cc.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.8/spconv/__version__.py -> build/bdist.linux-x86_64/wheel/spconv
running install_egg_info
removing 'build/bdist.linux-x86_64/wheel/spconv-2.1.21-py3.8.egg-info' (and everything under it)
Copying spconv.egg-info to build/bdist.linux-x86_64/wheel/spconv-2.1.21-py3.8.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 194, in <module>
    setup(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 351, in run
    self.egg2dist(self.egginfo_dir, distinfo_dir)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 471, in egg2dist
    pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/wheel/metadata.py", line 70, in pkginfo_to_metadata
    pkg_info.replace_header('Metadata-Version', '2.1')
  File "/usr/local/miniconda3/lib/python3.8/email/message.py", line 558, in replace_header
    raise KeyError(_name)
KeyError: 'metadata-version'

here is my package version:
cumm                     0.2.8
wheel                    0.37.1
ccimport               0.3.7
setuptools               58.0.4
pccm                     0.3.4

**Comment by Duan-AI-study** [comment]
Dear developer, there still have some trouble when installing spconv-plus.   import sopconv.core_cc as _ext  importerror:arg():could not convert default argument 'timer:tv::cudakerneltimer' in method '<class' spconv.core_cc.cumm.gemm.main.GemmParams'>.__init__' into a python object ( type not registered yet?)
