### ISSUE TITLE
ValueError: /io/include/tensorview/tensor.h(171) don't compiled with cuda

### ISSUE THREAD

**Issue by fjzpcmj** [dvlab-research/spconv-plus#5]
Dear authors, I install spconv-plus and run the script examples.py,  but there are something wrong. 
here is my package info:
cuda=11.3
torch=1.10.0
torch.version.cuda=11.3

python examples.py 
[Exception|indice_conv]feat=torch.Size([240000, 32]),w=torch.Size([3, 3, 3, 32, 32]),pair=torch.Size([2, 27, 240000]),pairnum=tensor([  5527,   6017,   5605,   5576,   6206,   5602,   5575,   6049,   5587,
          5673,   5994,   5628,   5615, 120000,   5518,   5550,   6006,   5685,
          5542,   5851,   5650,   5649,   6037,   5648,   5643,   5995,   5489],
       device='cuda:0', dtype=torch.int32),act=240000,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "examples.py", line 313, in <module>
    main_spss(algo=spconv.ConvAlgo.Native, dtype=torch.float32, pruning_ratio=0.5)
  File "examples.py", line 194, in main_spss
    out = net(features_t, indices_t, bs, pruning_ratio=pruning_ratio)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "examples.py", line 59, in forward
    return self.net(x, mask)  # .dense()
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 372, in forward
    out_features = conv_func(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 84, in forward
    raise e 
  File "/usr/local/miniconda3/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 69, in forward
    return conv_func(features,
  File "/usr/local/miniconda3/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 767, in indice_conv
    tuned_res, min_time = GEMM.tune_and_cache(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/spconv/algo.py", line 324, in tune_and_cache
    c_ = c.clone()
ValueError: /io/include/tensorview/tensor.h(171)
don't compiled with cuda

**Comment by Ricky846** [comment]
Have you solved this issue?I have the same issue and our package are the same. Thx!

**Comment by hontrn9122** [comment]
You have to specify your Cuda version before compiling cumm and spconv-plus.

`export CUMM_CUDA_VERSION="your cuda version"`
`export CUMM_DISABLE_JIT="1"`
`export SPCONV_DISABLE_JIT="1"`

Now you can rebuild and install cumm and spconv-plus from source. It should work fine.
